[profile.default]
remappings = [
    "v3-core/contracts=lib/v3-core/contracts",
    "v3-periphery/contracts=lib/v3-periphery/contracts",
    "swap-router-contracts/contracts=lib/swap-router-contracts/contracts",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
]

src = "src"
out = "out"
libs = ["lib"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
